### PR TITLE
Added Neighborhoods at Risk card to next steps section

### PR DESCRIPTION
**Pull request by wrdaigle**

### CODE REVIEW

**Comment by wrdaigle** [comment]
@cmy2k, here is the Neighborhoods at Risk card that we talked about earlier this year.  Take a look and let me know what you think.  We can tweak as necessary.

**Comment by wrdaigle** [comment]
Here is a quick demo...

https://user-images.githubusercontent.com/1017678/119601264-0a4d7000-bda6-11eb-8273-5e1560422fc2.mov

**Comment by Irantwomiles** [comment]
Thanks for the pull request @wrdaigle

**Comment by jwilson8767** [comment]
@wrdaigle Just a heads-up that we have deployed these changes over here for testing and review: https://climate-explorer.fernleafinteractive.com/next_steps/?county=New+York+County&city=New+York%2C+NY&fips=36061&lat=40.7127753&lon=-74.0059728

By and large, this was drop-in. I did add some extra code to handle window resizing / responsiveness. Really great work! Thanks so much!

**Comment by wrdaigle** [comment]
Thanks @jwilson8767!

**Pull request merged**
